init modified

diff --git a/frontend/deployment.yaml b/frontend/deployment.yaml
--- a/frontend/deployment.yaml
+++ b/frontend/deployment.yaml
@@ -83,61 +83,64 @@ spec:
       - name: targetgroup-volume
         emptyDir: {}  # Empty directory volume for storing the target group YAML
 
-      initContainers:
-      - name: fetch-parameter-store
-        image: amazon/aws-cli:latest
-        command:
-        - "/bin/sh"
-        - "-c"
-        - |
+  initContainers:
+  - name: fetch-parameter-store
+    image: amazon/aws-cli:latest
+    command:
+      - "/bin/sh"
+      - "-c"
+      - |
         # Install kubectl
-         echo "Installing kubectl..."
-         curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl"
-         chmod +x ./kubectl
-         mv ./kubectl /usr/local/bin/kubectl
+        echo "Installing kubectl..."
+        curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl"
+        chmod +x ./kubectl
+        mv ./kubectl /usr/local/bin/kubectl
         
-         # Fetch ARN from AWS SSM Parameter Store
-         echo "Fetching ARN from AWS SSM Parameter Store..."
-         TG_ARN=$(aws ssm get-parameter \
+        # Fetch ARN from AWS SSM Parameter Store
+        echo "Fetching ARN from AWS SSM Parameter Store..."
+        TG_ARN=$(aws ssm get-parameter \
           --name "/expense/dev/aws_lb_target_group_arn" \
           --with-decryption \
           --query "Parameter.Value" \
           --output text)
-            
-        # Check if ARN retrieval was successful
-            if [ -z "$TG_ARN" ]; then
-              echo "Error: Failed to retrieve ARN from SSM."
-              exit 1
-            fi
-            echo "Successfully fetched ARN: $TG_ARN"
-            # Create the TargetGroupBinding YAML template with the fetched ARN
-            cat <<EOF > /tmp/targetgroup-volume/target-group.yaml
-            apiVersion: elbv2.k8s.aws/v1beta1
-            kind: TargetGroupBinding
-            metadata:
-                  name: frontend
-                  namespace: expense
-            spec:
-              serviceRef:
-                    name: frontend # route traffic to the frontend service
-                    port: 80
-              targetGroupARN: ${TG_ARN}
-            EOF
 
-            echo "Applied TargetGroupBinding successfully to the Kubernetes cluster."
-            kubectl apply -f /tmp/targetgroup-volume/target-group.yaml
-            
-        resources:
-            limits:
-              memory: "64Mi"
-              cpu: "50m"
-            requests:
-              memory: "32Mi"
-              cpu: "20m"
-        volumeMounts:
-          - name: targetgroup-volume
-            mountPath: /tmp/targetgroup-volume
-            readOnly: false
+        # Check if ARN retrieval was successful
+        if [ -z "$TG_ARN" ]; then
+          echo "Error: Failed to retrieve ARN from SSM."
+          exit 1
+        fi
+        echo "Successfully fetched ARN: $TG_ARN"
+
+        # Create the TargetGroupBinding YAML template with the fetched ARN
+        cat <<EOF > /tmp/targetgroup-volume/targetgroup.yaml
+        apiVersion: elbv2.k8s.aws/v1beta1
+        kind: TargetGroupBinding
+        metadata:
+          name: frontend
+          namespace: expense
+        spec:
+          serviceRef:
+            name: frontend
+            port: 80
+          targetGroupARN: ${TG_ARN}
+        EOF
+
+        echo "Applied TargetGroupBinding successfully to the Kubernetes cluster."
+
+        # Apply the generated targetgroup.yaml to the Kubernetes cluster
+        kubectl apply -f /tmp/targetgroup-volume/targetgroup.yaml
+    resources:
+      limits:
+        cpu: "50m"
+        memory: "64Mi"
+      requests:
+        cpu: "20m"
+        memory: "32Mi"
+    volumeMounts:
+      - name: targetgroup-volume
+        mountPath: /tmp/targetgroup-volume
+        readOnly: false  # Set to false so it can write to the volume
+
       # env:
       #   - name: AWS_REGION
       #     value: us-east-1
@@ -151,7 +154,7 @@ spec:
       #       secretKeyRef:
       #         name: aws-credentials
       #         key: aws_secret_access_key
-      containers:
+    containers:
       - name: nginx
         image: bhavyasomisetti/frontend:1.1.0
         resources:
